services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod

    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Database__Migrate: ${DATABASE_MIGRATE:-true}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod

    ports:
      - "${FRONTEND_BIND_ADDRESS:-127.0.0.1}:${FRONTEND_PORT:-5173}:80"
